#!/usr/bin/env bash
# Mac-side: gather credentials and write the box's .env. Prints key names
# only, never values.
#
# Sources:
#   Zulip (bot) + Brave   ~/Documents/Research/polynumeral-assistant/.env
#   OpenRouter key         ~/.pi/agent/auth.json
#   Kagi key               1Password (op://librechat/kagi_api_key/credential)
#                          — only if the 1Password CLI is signed in; the box
#                          stays on Brave otherwise. To switch: sign in to the
#                          1Password CLI (or paste the key into this script's
#                          KAGI_MANUAL var) and re-run; SEARCH_PROVIDER flips.
set -euo pipefail

REMOTE_HOST=root@128.140.54.129
REMOTE_DIR=/opt/family-agent
PENV="$HOME/Documents/Research/polynumeral-assistant/.env"

# Your Zulip email(s), comma-separated: the bot adds you to streams it
# creates and to any configured stream you are missing.
OWNER_EMAILS="user1031086@polynumeral.zulipchat.com"

# Optional: paste the Kagi API key here to switch without 1Password.
KAGI_MANUAL=""

[ -f "$PENV" ] || { echo "missing $PENV" >&2; exit 1; }

OUT=$(mktemp)
trap 'rm -f "$OUT" "$OUT.assign"' EXIT

python3 - "$PENV" > "$OUT.assign" <<'PY'
import sys, shlex
vals = {}
for line in open(sys.argv[1]):
    line = line.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    k, v = line.split("=", 1)
    vals[k] = v
for k in ("ZULIP_SITE", "ZULIP_EMAIL", "ZULIP_API_KEY", "BRAVE_API_KEY"):
    print(k + "=" + shlex.quote(vals.get(k, "")))
PY
source "$OUT.assign"

OPENROUTER_API_KEY=$(python3 -c "
import json
print(json.load(open('$HOME/.pi/agent/auth.json'))['openrouter']['key'])
")

KAGI_API_KEY=""
if [ -n "$KAGI_MANUAL" ]; then
  KAGI_API_KEY="$KAGI_MANUAL"
elif command -v op >/dev/null 2>&1; then
  # Non-interactive attempt: fails fast when signed out, waits when locked.
  if KAGI_API_KEY=$(op read "op://librechat/kagi_api_key/credential" 2>/dev/null); then
    :
  else
    KAGI_API_KEY=""
  fi
fi
if [ -n "$KAGI_API_KEY" ]; then
  SEARCH_PROVIDER="kagi"
  echo "search provider: kagi (key found)"
else
  SEARCH_PROVIDER="brave"
  echo "search provider: brave (no Kagi key: 1Password CLI signed out and KAGI_MANUAL empty)" >&2
fi

for name in ZULIP_SITE ZULIP_EMAIL ZULIP_API_KEY OPENROUTER_API_KEY; do
  val="${!name}"
  if [ -z "$val" ]; then echo "WARNING: $name is empty" >&2; fi
done

cat > "$OUT" <<EOF
# family-agent Phase 1 — generated by push-secrets.sh $(date -u +%FT%TZ)
# Contains secrets: keep at mode 600.

# Zulip (main bot user)
ZULIP_SITE=$ZULIP_SITE
ZULIP_EMAIL=$ZULIP_EMAIL
ZULIP_API_KEY=$ZULIP_API_KEY

# Users the bot adds to streams it joins or creates (comma-separated).
ZULIP_OWNER_EMAILS=$OWNER_EMAILS

# Gateway config
EXEC_IMAGE=family-agent-exec:latest
WORKSPACES_DIR=/opt/family-agent/workspaces
DURABLE_DIR=/opt/family-agent/durable
IDLE_MINUTES=30
LOG_LEVEL=info
TZ=America/New_York

# LLM
OPENROUTER_API_KEY=$OPENROUTER_API_KEY

# Search: provider follows whichever key is available.
SEARCH_PROVIDER=$SEARCH_PROVIDER
KAGI_API_KEY=$KAGI_API_KEY
BRAVE_API_KEY=$BRAVE_API_KEY
EOF

ssh "$REMOTE_HOST" "mkdir -p $REMOTE_DIR && cat > $REMOTE_DIR/.env && chmod 600 $REMOTE_DIR/.env" < "$OUT"
echo "wrote $REMOTE_HOST:$REMOTE_DIR/.env (search: $SEARCH_PROVIDER)"
