#!/usr/bin/env bash
# Mac-side: gather credentials from existing local sources and write the
# box .env. Prints key names only, never values.
#
# Sources:
#   Zulip (bot) + Brave   ~/Documents/Research/polynumeral-assistant/.env
#   OpenRouter key         ~/.pi/agent/auth.json
#
# Tonight the nanobot Fly machines are stopped, so the main bot user is
# free for the gateway (see runbook).
set -euo pipefail

REMOTE_HOST=root@128.140.54.129
REMOTE_DIR=/opt/family-agent
PENV="$HOME/Documents/Research/polynumeral-assistant/.env"

[ -f "$PENV" ] || { echo "missing $PENV" >&2; exit 1; }

OUT=$(mktemp)
trap 'rm -f "$OUT" "$OUT.assign"' EXIT

# Extract values without echoing them: python writes shell assignments
# to a temp file, which is then sourced.
python3 - "$PENV" > "$OUT.assign" <<'PY'
import sys, shlex
vals = {}
for line in open(sys.argv[1]):
    line = line.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    k, v = line.split("=", 1)
    vals[k] = v
for k in ("ZULIP_SITE", "ZULIP_EMAIL", "ZULIP_API_KEY", "BRAVE_API_KEY"):
    print(k + "=" + shlex.quote(vals.get(k, "")))
PY
source "$OUT.assign"

OPENROUTER_API_KEY=$(python3 -c "
import json
print(json.load(open('$HOME/.pi/agent/auth.json'))['openrouter']['key'])
")

for name in ZULIP_SITE ZULIP_EMAIL ZULIP_API_KEY BRAVE_API_KEY OPENROUTER_API_KEY; do
  val="${!name}"
  if [ -z "$val" ]; then echo "WARNING: $name is empty" >&2; fi
done

cat > "$OUT" <<EOF
# family-agent Phase 1 — generated by push-secrets.sh $(date -u +%FT%TZ)
# Contains secrets: keep at mode 600.

# Zulip (main bot user; nanobot machines are stopped)
ZULIP_SITE=$ZULIP_SITE
ZULIP_EMAIL=$ZULIP_EMAIL
ZULIP_API_KEY=$ZULIP_API_KEY

# Add your own Zulip email(s), comma-separated, so the bot can add you to
# the scratch stream on startup. Empty = subscribe manually in Zulip.
ZULIP_OWNER_EMAILS=

# Gateway config
SCRATCH_STREAM=scratch
SESSION_IMAGE=family-agent-session:latest
WORKSPACE_DIR=/opt/family-agent/workspace
SESSIONS_DIR=/opt/family-agent/sessions
IDLE_MINUTES=30
LOG_LEVEL=info
TZ=America/New_York

# LLM
OPENROUTER_API_KEY=$OPENROUTER_API_KEY

# Search MCP: brave works tonight; flip to kagi in the morning by filling
# the key and changing SEARCH_PROVIDER.
SEARCH_PROVIDER=brave
KAGI_API_KEY=
BRAVE_API_KEY=$BRAVE_API_KEY
EOF

ssh "$REMOTE_HOST" "mkdir -p $REMOTE_DIR && cat > $REMOTE_DIR/.env && chmod 600 $REMOTE_DIR/.env" < "$OUT"
echo "wrote $REMOTE_HOST:$REMOTE_DIR/.env (keys: ZULIP_SITE ZULIP_EMAIL ZULIP_API_KEY BRAVE_API_KEY OPENROUTER_API_KEY)"
